
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Jan 26 16:37:04 CET 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 13;
  public static final int DIVIDE = 9;
  public static final int LBRACKET = 24;
  public static final int CHAR = 37;
  public static final int CONST = 18;
  public static final int NOTEQUAL = 22;
  public static final int DBLEQUAL = 19;
  public static final int LESS = 14;
  public static final int MINUS = 4;
  public static final int SEMICOLON = 16;
  public static final int RPAR = 29;
  public static final int BOOL = 35;
  public static final int COMMA = 17;
  public static final int LESSOREQUAL = 11;
  public static final int PLUS = 12;
  public static final int DOT = 6;
  public static final int GRATHER = 20;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 15;
  public static final int RETURN = 31;
  public static final int RBRACKET = 25;
  public static final int EQUAL = 23;
  public static final int NEW = 3;
  public static final int error = 1;
  public static final int PERCENT = 10;
  public static final int NUMBER = 34;
  public static final int IDENT = 36;
  public static final int VOID = 27;
  public static final int MULTIPLE = 8;
  public static final int COLON = 30;
  public static final int LBRACE = 5;
  public static final int READ = 32;
  public static final int GOTO = 33;
  public static final int GRATHEROREQUAL = 21;
  public static final int RBRACE = 7;
  public static final int PROG = 2;
  public static final int LPAR = 28;
  public static final int PRINT = 26;
}

